# .bashrc
# Author: Denis Ciccale (@tdecs)
# Source: http://github.com/dciccale/dotfiles/blob/master/.bashrc

export TERM=xterm-256color
export EDITOR="mvim"

# colors
PURPLE="$(tput setaf 5)"
DARKGREY="$(tput setaf 8)"
WHITE="$(tput setaf 7)"
YELLOW="$(tput setaf 3)"
BLUE="$(tput setaf 4)"
GREEN="$(tput setaf 2)"
RESET="$(tput sgr0)"

# load bash aliases
if [ -f ~/.aliases ]; then . ~/.aliases; fi

export MOAI_BIN="${HOME}/Downloads/moai-sdk/bin/osx"
PATH=/usr/local/mysql/bin:$PATH:$MOAI_BIN
PATH=/usr/local/git/bin:/usr/local/sbin:$PATH
PATH=/usr/local/bin:$PATH
PATH=${HOME}/.rvm/bin:$PATH
PATH=${HOME}/tizen-sdk/tools/ide/bin:$PATH
PATH=${HOME}/ant/bin:$PATH
PATH=/usr/local/php5/bin:$PATH

. ~/.rvm/scripts/rvm

function parse_git_dirty() {
  git diff --quiet --ignore-submodules HEAD 2>/dev/null; [ $? -eq 1 ] && echo "*"
}

function parse_git_branch() {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}

function prompt() {
  LEFT=${PWD/$HOME/'~'} # current dir
  RIGHT=$(parse_git_branch) # git branch
  COLS=$(($(tput cols)-${#LEFT}+${#PURPLE})) # calculated columns
  printf '%s%*s%s%s' "${YELLOW}${LEFT}" ${COLS} "${PURPLE}${RIGHT}"
}

PROMPT_COMMAND=prompt
PS1="\n\n\[${DARKGREY}\]>\[${RESET}\] "
PS2='+ '

## Tizen SDK configuration
# This is generated by Tizen SDK. Please do not modify by yourself.
# Set sdb environment path
export PATH=$PATH:${HOME}/tizen-sdk/tools
## End Tizen SDK configuration

# Export easy way to open my gitconfig
export GIT_CONFIG=${HOME}/.gitconfig

# Export my .bashrc file path
export MYBASHRC=${HOME}/.bashrc

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
