# .bashrc
# Author: Denis Ciccale (@tdecs)
# Source: http://github.com/dciccale/dotfiles/blob/master/.bashrc

export TERM=xterm-256color
export EDITOR="mvim"
export FIGNORE=DS_Store

# colors
PURPLE="$(tput setaf 5)"
DARKGREY="$(tput setaf 8)"
WHITE="$(tput setaf 7)"
YELLOW="$(tput setaf 3)"
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
BLUE="$(tput setaf 4)"
RESET="$(tput sgr0)"

# load bash aliases
if [ -f ~/.aliases ]; then . ~/.aliases; fi

export MOAI_BIN="${HOME}/Downloads/moai-sdk/bin/osx"
PATH=/usr/local/mysql/bin:$PATH
PATH=$MOAI_BIN:$PATH
PATH=/usr/local/git/bin:/usr/local/sbin:$PATH
PATH=/usr/local/bin:$PATH
PATH=${HOME}/.rvm/bin:$PATH
PATH=${HOME}/tizen-sdk/tools/ide/bin:$PATH
PATH=${HOME}/ant/bin:$PATH
PATH=/usr/local/php5/bin:$PATH

. ~/.rvm/scripts/rvm

function parse_git_dirty() {
  git diff --quiet --ignore-submodules HEAD &>/dev/null; [ $? -eq 1 ] && echo "*"
}

checkpull() {
 [ $(git rev-parse HEAD) != $(git rev-parse @{u}) ] && echo "⇣"
}

function parse_git_branch() {
  # check if we're in a git repo
  git rev-parse --is-inside-work-tree &>/dev/null || return

  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$(parse_git_dirty)/"
}

function prompt() {
  LEFT=${PWD/$HOME/'~'} # current dir
  RIGHT=$(parse_git_branch) # git branch
  COLS=$(($(tput cols)-${#LEFT}+${#PURPLE})) # calculated columns
  # print -Pn "\e7\e[A\e[1G\e["asd"C%F{cyan}⇣%f\e8"
  P=$(printf '%s%*s%s%s' "${YELLOW}${LEFT}" ${COLS} "${PURPLE}${RIGHT}")
  printf "\n${P}${RESET}\n\n"
  # echo -en "\n${P}${RESET}\n\n"
}

PROMPT_COMMAND=prompt
PS1="\[${DARKGREY}\]❯\[${RESET}\] "
PS2="\[${RED}\]❯\[${RESET}\] "

## Tizen SDK configuration
# This is generated by Tizen SDK. Please do not modify by yourself.
# Set sdb environment path
export PATH=$PATH:${HOME}/tizen-sdk/tools
## End Tizen SDK configuration

# Export easy way to open my gitconfig
export GIT_CONFIG=${HOME}/.gitconfig

# Export my .bashrc file path
export MYBASHRC=${HOME}/.bashrc

# Export my .aliases file path
export MYALIASES=${HOME}/.aliases

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
